In [43]:
import duckdb
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo
import os

In [44]:
WAREHOUSE_TEST = "./test_duckdb_data/gtftestha.duckdb"

con = duckdb.connect(WAREHOUSE_TEST)
con.execute("SET TimeZone='UTC';")

con.sql("SHOW TABLES").df()

                           name
0                        agency
1                      calendar
2                calendar_dates
3   delays_with_support_columns
4                     feed_info
5                        routes
6                        shapes
7                    stop_times
8                         stops
9                         trips
10                trips_updates
11            vehicle_positions

In [37]:
con.sql("SELECT * FROM stops LIMIT 10").df()

,stop_id,stop_code,stop_name,stop_lat,stop_lon,zone_id,location_type,parent_station,stop_timezone,wheelchair_boarding
0,1,ABBAT8,Abattoirs,43.717886,7.284703,None,0,place_101376,None,1
1,2,ABBAT4,Abattoirs,43.718399,7.284448,None,0,place_101376,None,1
2,3,ROSEL2,Abbaye de Roseland,43.693389,7.228426,None,0,place_096609,None,0
3,4,ROSEL8,Abbaye de Roseland,43.693219,7.228365,None,0,place_096609,None,0
4,5,ARSE4,Abbaye de Roseland / Napoléon III,43.688851,7.231361,None,0,place_096610,None,0
5,6,ACROB6,Risso,43.703344,7.280371,None,0,place_096612,None,1
6,8,AEPRM1,Aéroport / Promenade,43.666336,7.212338,None,0,place_101377,None,1
7,11,AEPRM2,Aéroport / Promenade,43.666523,7.212107,None,0,place_101377,None,1
8,12,ALBER3,Albert 1er,43.69585,7.269182,None,0,place_096616,None,0
9,13,ALBER8,Jardin d'Arménie,43.695717,7.2666,None,0,place_096617,None,0

In [51]:
# time reel
con.sql("""
CREATE OR REPLACE VIEW actual AS
SELECT
  tu.trip_id,
  tu.stop_sequence,
  CAST(tu.arrival_dt AS TIMESTAMP WITH TIME ZONE) AS arrival_dt_utc
FROM trips_updates tu
WHERE tu.arrival_dt IS NOT NULL;
""")

con.sql("SELECT * FROM actual LIMIT 10").df()

,trip_id,stop_sequence,arrival_dt_utc
0,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,1,2025-09-11 11:45:42+00:00
1,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,2,2025-09-11 11:45:55+00:00
2,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,3,2025-09-11 11:46:44+00:00
3,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,4,2025-09-11 11:47:48+00:00
4,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,5,2025-09-11 11:48:50+00:00
5,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,6,2025-09-11 11:50:14+00:00
6,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,7,2025-09-11 11:51:09+00:00
7,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,8,2025-09-11 11:51:46+00:00
8,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,9,2025-09-11 11:52:12+00:00
9,5673239-NVN1_R_98_NVN101_13:45-PROJET2024-NVen...,11,2025-09-11 11:53:45+00:00

In [52]:
# time theorique
con.sql("""
CREATE OR REPLACE VIEW sched AS
SELECT
  st.trip_id,
  CAST(st.stop_sequence AS BIGINT) AS stop_sequence,
  st.stop_id,
  st.arrival_time_sec
FROM stop_times st
WHERE st.arrival_time_sec IS NOT NULL;
""")

con.sql("SELECT * FROM sched LIMIT 10").df()

,trip_id,stop_sequence,stop_id,arrival_time_sec
0,3064029-C32_A_1_C3201_08:30-RESEAU2021-C32-Lun...,0,21681,30600
1,3064029-C32_A_1_C3201_08:30-RESEAU2021-C32-Lun...,1,21652,30900
2,3064029-C32_A_1_C3201_08:30-RESEAU2021-C32-Lun...,2,21644,32100
3,3064029-C32_A_1_C3201_08:30-RESEAU2021-C32-Lun...,3,21398,33300
4,3064030-C32_R_2_C3202_17:20-RESEAU2021-C32-Lun...,0,21398,62400
5,3064030-C32_R_2_C3202_17:20-RESEAU2021-C32-Lun...,1,21644,63600
6,3064030-C32_R_2_C3202_17:20-RESEAU2021-C32-Lun...,2,21652,64800
7,3064030-C32_R_2_C3202_17:20-RESEAU2021-C32-Lun...,3,21681,65100
8,3064033-C32_A_1_C3202_17:00-RESEAU2021-C32-Wee...,0,21681,61200
9,3064033-C32_A_1_C3202_17:00-RESEAU2021-C32-Wee...,1,21652,61500

In [53]:
#join entre deux tables

con.sql("""
CREATE OR REPLACE VIEW joined AS
SELECT
  a.trip_id,
  a.stop_sequence,
  s.stop_id,
  a.arrival_dt_utc,
  CAST(a.arrival_dt_utc AT TIME ZONE 'Europe/Paris' AS DATE) AS local_service_day,
  s.arrival_time_sec
FROM actual a
JOIN sched s
  ON a.trip_id = s.trip_id
 AND a.stop_sequence = s.stop_sequence;
""")

con.sql("SELECT * FROM joined LIMIT 10").df()

,trip_id,stop_sequence,stop_id,arrival_dt_utc,local_service_day,arrival_time_sec
0,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,0,21583,2025-09-11 10:31:26+00:00,2025-09-11,45060
1,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,1,21261,2025-09-11 10:31:26+00:00,2025-09-11,45120
2,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,2,21265,2025-09-11 10:32:05+00:00,2025-09-11,45120
3,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,3,21266,2025-09-11 10:32:31+00:00,2025-09-11,45120
4,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,4,21267,2025-09-11 10:32:58+00:00,2025-09-11,45180
5,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,5,21268,2025-09-11 10:33:25+00:00,2025-09-11,45240
6,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,6,21269,2025-09-11 10:34:01+00:00,2025-09-11,45240
7,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,7,21270,2025-09-11 10:34:23+00:00,2025-09-11,45240
8,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,8,21271,2025-09-11 10:34:56+00:00,2025-09-11,45300
9,5203700-68_R_99_6802_12:31-PROJET2024-68-Semai...,9,21272,2025-09-11 10:35:35+00:00,2025-09-11,45360

In [81]:
# retard moyens reel - delay-min

con.sql("""
CREATE OR REPLACE VIEW per_event AS
SELECT
  trip_id,
  stop_sequence,
  stop_id,
  arrival_dt_utc,
  (
    (local_service_day + arrival_time_sec * INTERVAL '1 second')
    AT TIME ZONE 'Europe/Paris'
  ) AS scheduled_ts_utc,
  EXTRACT(
    EPOCH FROM (
      arrival_dt_utc - (
        (local_service_day + arrival_time_sec * INTERVAL '1 second')
        AT TIME ZONE 'Europe/Paris'
      )
    )
  ) / 60.0 AS delay_min
FROM joined;
""")

con.sql("SELECT * FROM per_event ORDER BY arrival_dt_utc DESC LIMIT 50").df()

,trip_id,stop_sequence,stop_id,arrival_dt_utc,scheduled_ts_utc,delay_min
0,4542749-44_R_99_4401_14:18-RESEAU2023-44-Semai...,7,4145,2025-09-11 12:44:41+00:00,2025-09-11 12:25:00+00:00,19.683333
1,4542693-44_A_50_4401_14:10-RESEAU2023-44-Semai...,7,4135,2025-09-11 12:33:42+00:00,2025-09-11 12:18:00+00:00,15.700000
2,6218561-84_R_95_8403_13:56-PROJET2025-84-Semai...,33,74,2025-09-11 12:30:32+00:00,2025-09-11 12:30:00+00:00,0.533333
3,6077772-58_A_50_5802_14:20-PROJET2025-58-Semai...,10,5162,2025-09-11 12:30:32+00:00,2025-09-11 12:31:00+00:00,-0.466667
4,4669793-62_A_46_6202_14:00-RESEAU2023-62-Semai...,28,6099,2025-09-11 12:30:27+00:00,2025-09-11 12:30:00+00:00,0.450000
5,6416089-21_R_99_2104_14:02-SETP2025-21-Semaine-40,20,4006,2025-09-11 12:30:25+00:00,2025-09-11 12:30:00+00:00,0.416667
6,6428320-60_A_50_6001_14:10-PROJET2025-60-Semai...,20,2546,2025-09-11 12:30:09+00:00,2025-09-11 12:30:00+00:00,0.150000
7,6368868-09_R_99_0904_13:55-PROJET2025-09-Semai...,19,4269,2025-09-11 12:30:09+00:00,2025-09-11 12:30:00+00:00,0.150000
8,6355833-18_A_50_1802_13:59-SETP2025-18-Semaine-39,26,376,2025-09-11 12:30:06+00:00,2025-09-11 12:30:00+00:00,0.100000
9,6446507-05_A_98_0509_14:03-SETP2025-05-L-Ma-J-...,21,1144,2025-09-11 12:30:00+00:00,2025-09-11 12:30:00+00:00,0.000000
10,6369772-42_A_5_4203_14:00-PROJET2025-42-Semain...,22,5001,2025-09-11 12:30:00+00:00,2025-09-11 12:30:00+00:00,0.000000
11,5759390-NVN2_A_50_NVN201_14:20-PROJET2024-NVen...,9,3263,2025-09-11 12:29:55+00:00,2025-09-11 12:30:00+00:00,-0.083333
12,6428099-98_A_50_9806_14:10-SETP2025-98-Semaine-08,24,541,2025-09-11 12:29:54+00:00,2025-09-11 12:42:00+00:00,-12.100000
13,5097936-69_R_90_6901_14:25-PROJET2023-69-Semai...,5,21594,2025-09-11 12:29:53+00:00,2025-09-11 12:30:00+00:00,-0.116667
14,6252990-14_A_50_1402_14:12-SETP2025-14-L-Ma-J-...,15,248,2025-09-11 12:29:53+00:00,2025-09-11 12:30:00+00:00,-0.116667
15,6446520-05_R_50_0501_14:16-SETP2025-05-L-Ma-J-...,12,1164,2025-09-11 12:29:49+00:00,2025-09-11 12:30:00+00:00,-0.183333
16,6416304-51_R_98_5104_14:16-PROJET2025-51-Semai...,16,167,2025-09-11 12:29:45+00:00,2025-09-11 12:30:00+00:00,-0.250000
17,6419999-35_A_50_3503_14:11-SETP2025-35-Semaine-35,14,1095,2025-09-11 12:29:43+00:00,2025-09-11 12:30:00+00:00,-0.283333
18,6429325-15_R_99_1508_14:28-SETP2025-15-Semaine-11,2,8095,2025-09-11 12:29:43+00:00,2025-09-11 12:30:00+00:00,-0.283333
19,6412280-71_A_50_7101_14:20-PROJET2025-71-Semai...,11,386,2025-09-11 12:29:42+00:00,2025-09-11 12:30:00+00:00,-0.300000
20,4542748-44_R_99_4401_13:53-RESEAU2023-44-Semai...,7,4145,2025-09-11 12:29:41+00:00,2025-09-11 12:00:00+00:00,29.683333
21,6369756-42_R_95_4201_13:42-PROJET2025-42-Semai...,37,4028,2025-09-11 12:29:38+00:00,2025-09-11 12:31:00+00:00,-1.366667
22,6218561-84_R_95_8403_13:56-PROJET2025-84-Semai...,30,1403,2025-09-11 12:29:35+00:00,2025-09-11 12:28:00+00:00,1.583333
23,4759139-47_A_50_4701_14:23-PROJET2023-47-Semai...,9,21197,2025-09-11 12:29:33+00:00,2025-09-11 12:29:00+00:00,0.550000
24,6416360-51_A_49_5105_14:18-PROJET2025-51-Semai...,8,804,2025-09-11 12:29:22+00:00,2025-09-11 12:29:00+00:00,0.366667
25,6327135-17_A_50_1704_14:04-SETP2025-17-L-Ma-J-...,19,562,2025-09-11 12:29:16+00:00,2025-09-11 12:29:00+00:00,0.266667
26,6368888-09_R_98_0902_14:10-PROJET2025-09-Semai...,9,4061,2025-09-11 12:29:13+00:00,2025-09-11 12:29:00+00:00,0.216667
27,6412280-71_A_50_7101_14:20-PROJET2025-71-Semai...,10,1370,2025-09-11 12:29:10+00:00,2025-09-11 12:29:00+00:00,0.166667
28,6416437-33_A_50_3302_14:06-SETP2025-33-L-Ma-J-...,21,429,2025-09-11 12:29:09+00:00,2025-09-11 12:29:00+00:00,0.150000
29,6327217-17_R_99_1703_14:15-SETP2025-17-L-Ma-J-...,10,1377,2025-09-11 12:29:00+00:00,2025-09-11 12:29:00+00:00,0.000000
30,6414285-07_R_97_0709_13:55-SETP2025-07-L-Ma-J-...,26,1065,2025-09-11 12:29:00+00:00,2025-09-11 12:29:00+00:00,0.000000
31,6446525-05_A_98_0504_14:19-SETP2025-05-L-Ma-J-...,6,321,2025-09-11 12:29:00+00:00,2025-09-11 12:29:00+00:00,0.000000
32,5838470-52_A_6_5201_14:00-PROJET2025-52-Semain...,32,1478,2025-09-11 12:29:00+00:00,2025-09-11 12:29:00+00:00,0.000000
33,5759390-NVN2_A_50_NVN201_14:20-PROJET2024-NVen...,8,3132,2025-09-11 12:28:58+00:00,2025-09-11 12:29:00+00:00,-0.033333
34,6077772-58_A_50_5802_14:20-PROJET2025-58-Semai...,8,5098,2025-09-11 12:28:57+00:00,2025-09-11 12:29:00+00:00,-0.050000
35,4515184-80_A_46_8001_14:10-RESEAU2023-80-Semai...,18,1399,2025-09-11 12:28:46+00:00,2025-09-11 12:29:00+00:00,-0.233333
36,5925303-54_R_99_5401_14:10-PROJET2025-54-Semai...,22,4117,2025-09-11 12:28:39+00:00,2025-09-11 12:29:00+00:00,-0.350000
37,6424101-16_A_50_1602_14:13-SETP2025-16-Semaine-35,15,482,2025-09-11 12:28:34+00:00,2025-09-11 12:29:00+00:00,-0.433333
38,6428441-61_R_99_6104_14:00-PROJET2025-61-Semai...,31,425,2025-09-11 12:28:20+00:00,2025-09-11 12:29:00+00:00,-0.666667
39,6462526-31_R_97_3102_14:15-PROJET2025-31-Semai...,16,361,2025-09-11 12:28:16+00:00,2025-09-11 12:28:00+00:00,0.266667
40,6218521-84_A_50_8401_14:20-PROJET2025-84-Semai...,13,7170,2025-09-11 12:28:13+00:00,2025-09-11 12:28:00+00:00,0.216667
41,6355793-18_R_99_1804_14:16-SETP2025-18-Semaine-39,10,787,2025-09-11 12:28:11+00:00,2025-09-11 12:28:00+00:00,0.183333
42,6102461-63_R_98_6302_14:20-PROJET2025-63-Semai...,10,591,2025-09-11 12:28:08+00:00,2025-09-11 12:28:00+00:00,0.133333
43,5909230-NVN3_A_90_NVN301_14:00-PROJET2025-NVen...,27,3234,2025-09-11 12:28:06+00:00,2025-09-11 12:28:00+00:00,0.100000
44,6410634-64_A_50_6402_14:15-SETP2025-64-Semaine-37,10,252,2025-09-11 12:28:04+00:00,2025-09-11 12:28:00+00:00,0.066667
45,6252990-14_A_50_1402_14:12-SETP2025-14-L-Ma-J-...,14,25,2025-09-11 12:28:00+00:00,2025-09-11 12:28:00+00:00,0.000000
46,4759149-47_R_99_4702_14:27-PROJET2023-47-Semai...,1,21231,2025-09-11 12:28:00+00:00,2025-09-11 12:28:00+00:00,0.000000
47,6428447-61_A_50_6105_14:10-PROJET2025-61-Semai...,21,994,2025-09-11 12:27:59+00:00,2025-09-11 12:28:00+00:00,-0.016667
48,6369757-42_R_95_4202_14:14-PROJET2025-42-Semai...,12,4105,2025-09-11 12:27:57+00:00,2025-09-11 12:29:00+00:00,-1.050000
49,5203710-68_R_99_6803_14:20-PROJET2024-68-Semai...,14,21277,2025-09-11 12:27:49+00:00,2025-09-11 12:28:00+00:00,-0.183333

In [79]:
con.execute("DROP VIEW IF EXISTS delays_with_support_columns;")
con.execute("DROP VIEW IF EXISTS per_event;")

test

In [82]:
# associer retards en utilisant la view insere dans duckdb (delays_with_support_columns)
con.sql("""
CREATE OR REPLACE VIEW stop_with_delay AS
SELECT
  s.stop_id,
  s.stop_name,
  s.stop_lat,
  s.stop_lon,
  ROUND(AVG(pe.delay_min), 2) AS avg_delay_min
FROM stops s
LEFT JOIN (
  SELECT * FROM per_event
  WHERE arrival_dt_utc::DATE = CURRENT_DATE
) pe
ON s.stop_id = pe.stop_id
GROUP BY s.stop_id, s.stop_name, s.stop_lat, s.stop_lon;
""")

con.sql("SELECT * FROM stop_with_delay ORDER BY avg_delay_min DESC LIMIT 10").df()

  stop_id          stop_name   stop_lat  stop_lon  avg_delay_min
0    5171   Sainte-Geneviève  43.695547  7.174875          41.01
1    5030  Corniche Bellevue  43.670837  7.184012          40.94
2    5050   Fahnestock Forêt  43.685251   7.17733          40.83
3    5108           Mauberts  43.688735  7.176725          40.74
4    5102          Li Maioun  43.680396  7.180559          40.73
5    5107    Mas de Montalou  43.683569  7.179403          40.66
6    5140   Rond Point Ravet   43.66875  7.184069          40.59
7    5047  Ecole Montaleigne  43.693593  7.175439          40.57
8    5085    Le Collet Rouge  43.697912  7.174152          40.50
9    5100          Les Tines  43.706529  7.171491          40.49

In [74]:
con.sql("""
SELECT 
  stop_id, 
  arrival_dt_utc,
  scheduled_ts_utc,
  delay_min
FROM per_event
WHERE arrival_dt_utc::DATE = CURRENT_DATE
ORDER BY delay_min DESC
LIMIT 50
""").df()

   stop_id            arrival_dt_utc          scheduled_ts_utc  delay_min
0     5171 2025-09-11 10:46:01+00:00 2025-09-11 09:18:00+00:00  88.016667
1     5050 2025-09-11 10:43:59+00:00 2025-09-11 09:16:00+00:00  87.983333
2     5030 2025-09-11 10:40:55+00:00 2025-09-11 09:13:00+00:00  87.916667
3     5088 2025-09-11 10:41:54+00:00 2025-09-11 09:14:00+00:00  87.900000
4     5028 2025-09-11 10:39:52+00:00 2025-09-11 09:12:00+00:00  87.866667
5     3106 2025-09-11 10:54:52+00:00 2025-09-11 09:27:00+00:00  87.866667
6     5254 2025-09-11 10:36:50+00:00 2025-09-11 09:09:00+00:00  87.833333
7     5253 2025-09-11 10:34:49+00:00 2025-09-11 09:07:00+00:00  87.816667
8     5143 2025-09-11 10:49:44+00:00 2025-09-11 09:22:00+00:00  87.733333
9     5102 2025-09-11 10:42:44+00:00 2025-09-11 09:15:00+00:00  87.733333
10    5108 2025-09-11 10:44:43+00:00 2025-09-11 09:17:00+00:00  87.716667
11    5100 2025-09-11 10:48:43+00:00 2025-09-11 09:21:00+00:00  87.716667
12    5140 2025-09-11 10:40:41+00:00 2025-09-11 09:13:00+00:00  87.683333
13    3049 2025-09-11 10:55:39+00:00 2025-09-11 09:28:00+00:00  87.650000
14    5103 2025-09-11 10:39:39+00:00 2025-09-11 09:12:00+00:00  87.650000
15    3061 2025-09-11 11:00:38+00:00 2025-09-11 09:33:00+00:00  87.633333
16    5107 2025-09-11 10:43:33+00:00 2025-09-11 09:16:00+00:00  87.550000
17    5097 2025-09-11 10:42:31+00:00 2025-09-11 09:15:00+00:00  87.516667
18    5085 2025-09-11 10:46:28+00:00 2025-09-11 09:19:00+00:00  87.466667
19    5047 2025-09-11 10:45:28+00:00 2025-09-11 09:18:00+00:00  87.466667
20    3006 2025-09-11 11:01:27+00:00 2025-09-11 09:34:00+00:00  87.450000
21    5123 2025-09-11 10:41:26+00:00 2025-09-11 09:14:00+00:00  87.433333
22    5098 2025-09-11 10:40:26+00:00 2025-09-11 09:13:00+00:00  87.433333
23    5176 2025-09-11 10:47:24+00:00 2025-09-11 09:20:00+00:00  87.400000
24    3119 2025-09-11 11:04:22+00:00 2025-09-11 09:37:00+00:00  87.366667
25    5033 2025-09-11 10:42:19+00:00 2025-09-11 09:15:00+00:00  87.316667
26    5221 2025-09-11 10:30:17+00:00 2025-09-11 09:03:00+00:00  87.283333
27    3047 2025-09-11 10:56:16+00:00 2025-09-11 09:29:00+00:00  87.266667
28    3009 2025-09-11 11:00:16+00:00 2025-09-11 09:33:00+00:00  87.266667
29    3024 2025-09-11 10:52:16+00:00 2025-09-11 09:25:00+00:00  87.266667
30    5255 2025-09-11 10:38:13+00:00 2025-09-11 09:11:00+00:00  87.216667
31    5083 2025-09-11 10:45:06+00:00 2025-09-11 09:18:00+00:00  87.100000
32    3116 2025-09-11 10:56:06+00:00 2025-09-11 09:29:00+00:00  87.100000
33    3045 2025-09-11 11:01:06+00:00 2025-09-11 09:34:00+00:00  87.100000
34    5113 2025-09-11 10:50:03+00:00 2025-09-11 09:23:00+00:00  87.050000
35    5049 2025-09-11 10:43:03+00:00 2025-09-11 09:16:00+00:00  87.050000
36    5075 2025-09-11 10:48:02+00:00 2025-09-11 09:21:00+00:00  87.033333
37    3037 2025-09-11 11:01:59+00:00 2025-09-11 09:35:00+00:00  86.983333
38    3069 2025-09-11 10:58:58+00:00 2025-09-11 09:32:00+00:00  86.966667
39    3094 2025-09-11 10:57:47+00:00 2025-09-11 09:31:00+00:00  86.783333
40    5252 2025-09-11 10:30:26+00:00 2025-09-11 09:06:00+00:00  84.433333
41    3007 2025-09-11 11:06:46+00:00 2025-09-11 09:45:00+00:00  81.766667
42    3105 2025-09-11 11:13:45+00:00 2025-09-11 09:52:00+00:00  81.750000
43    3068 2025-09-11 11:09:36+00:00 2025-09-11 09:48:00+00:00  81.600000
44    3060 2025-09-11 11:07:34+00:00 2025-09-11 09:46:00+00:00  81.566667
45    3093 2025-09-11 11:10:33+00:00 2025-09-11 09:49:00+00:00  81.550000
46    3046 2025-09-11 11:07:19+00:00 2025-09-11 09:46:00+00:00  81.316667
47    3025 2025-09-11 11:16:16+00:00 2025-09-11 09:55:00+00:00  81.266667
48    3048 2025-09-11 11:12:16+00:00 2025-09-11 09:51:00+00:00  81.266667
49    3230 2025-09-11 11:13:13+00:00 2025-09-11 09:52:00+00:00  81.216667

In [83]:
con.sql("""
SELECT
  j.trip_id,
  j.stop_sequence,
  j.stop_id,
  j.arrival_dt_utc,
  j.local_service_day,
  j.arrival_time_sec,
  ((local_service_day + arrival_time_sec * INTERVAL '1 second') AT TIME ZONE 'Europe/Paris') AS scheduled_ts_utc,
  arrival_dt_utc - ((local_service_day + arrival_time_sec * INTERVAL '1 second') AT TIME ZONE 'Europe/Paris') AS delay_duration
FROM joined j
WHERE arrival_dt_utc::DATE = CURRENT_DATE
ORDER BY delay_duration DESC
LIMIT 10;
""").df()

,trip_id,stop_sequence,stop_id,arrival_dt_utc,local_service_day,arrival_time_sec,scheduled_ts_utc,delay_duration
0,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,23,5171,2025-09-11 10:46:01+00:00,2025-09-11,40680,2025-09-11 09:18:00+00:00,0 days 01:28:01
1,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,19,5050,2025-09-11 10:43:59+00:00,2025-09-11,40560,2025-09-11 09:16:00+00:00,0 days 01:27:59
2,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,11,5030,2025-09-11 10:40:55+00:00,2025-09-11,40380,2025-09-11 09:13:00+00:00,0 days 01:27:55
3,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,13,5088,2025-09-11 10:41:54+00:00,2025-09-11,40440,2025-09-11 09:14:00+00:00,0 days 01:27:54
4,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,8,5028,2025-09-11 10:39:52+00:00,2025-09-11,40320,2025-09-11 09:12:00+00:00,0 days 01:27:52
5,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,31,3106,2025-09-11 10:54:52+00:00,2025-09-11,41220,2025-09-11 09:27:00+00:00,0 days 01:27:52
6,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,5,5254,2025-09-11 10:36:50+00:00,2025-09-11,40140,2025-09-11 09:09:00+00:00,0 days 01:27:50
7,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,4,5253,2025-09-11 10:34:49+00:00,2025-09-11,40020,2025-09-11 09:07:00+00:00,0 days 01:27:49
8,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,16,5102,2025-09-11 10:42:44+00:00,2025-09-11,40500,2025-09-11 09:15:00+00:00,0 days 01:27:44
9,5925326-54_A_47_5402_10:58-PROJET2025-54-Semai...,28,5143,2025-09-11 10:49:44+00:00,2025-09-11,40920,2025-09-11 09:22:00+00:00,0 days 01:27:44

Il ya un decalage de environ 88mins environ, donc c'est a cause de l'erreur de ne pas avoir considere les bus qui partent apres minuit